version: '3.8'

services:
  php:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-b-soft-tz
    volumes:
      - ./:/var/www
    ports:
      - "8124:80"
    networks:
      - b-soft-tz-network
    environment:
      PHP_INI_DISPLAY_ERRORS: "1"
      PHP_INI_MEMORY_LIMIT: "512M"
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: msdrf(*$)#kjls

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xsx^&^&*09890jhj
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: msdrf(*$)#kjls
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - b-soft-tz-network


networks:
  b-soft-tz-network:
    driver: bridge